manifest:

  remotes:
    - name: zephyrproject-rtos
      url-base: https://github.com/zephyrproject-rtos
    - name: mender
      url-base: https://github.com/lluiscampos

  projects:
    - name: zephyr
      remote: zephyrproject-rtos
      revision: v3.7.0
      import: true
    - name: mender-mcu
      remote: mender
      revision: MEN-7387-complete-qemu-build
      # TODO: move to mender-mcu for developer's sanity
      path: modules/mender-mcu
      import: true

  self:
    path: mender-mcu-integration
